### PR TITLE
Making things private to make go lint happier

### PR DESCRIPTION
**Pull request by freeformz**
I'm taking a look at cleaning up lumbermill and my first passes are to make govet / lint not complain.

### CODE REVIEW

**Comment by apg** [comment]
It's probably not the case that there are bits in lumbermill that are worth extracting for use as a library... So, I'm +1 on this.

**Comment by freeformz** [comment]
@apg even if there were, we should make them public then. The default of all public stems back to my own Go style back when, which AFAICT is non-idiomatic.

**Comment by apg** [comment]
Sure. I was more arguing that it may be the case that lumbermill should be structured with cmd/lumbermill/main.go and a library. I think this is likely not worth while, though.

**Comment by freeformz** [comment]
@apg possibly, but I think I'd still have the same argument. ;-)

**Pull request merged**
